import { createStyles } from '@mantine/core';

export default createStyles(() => ({
    container: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        height: 'auto',
        backgroundColor: '#2d2d2d',
        backgroundRepeat: 'no-repeat',
        backgroundSize: 'cover',
        margin: '0px',
        padding: '0px',
        perspective: '1000px',
    },
    card: {
        position: 'relative',
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        color: '#eee',
        borderRadius: '10px',
        boxShadow: '0px 30px 60px rgba(0, 0, 0, 0.1), 0px 30px 60px rgba(0, 0, 0, 0.5)',
        maxWidth: '300px',
        backdropFilter: 'blur(10px)',
        padding: '20px',
        transformStyle: 'preserve-3d',
        backfaceVisibility: 'hidden',
        overflow: 'hidden',
        transition: 'transform 0.1s ease, background-image 0.5s ease',
    },
    backgroundOverlay: {
        width: '100%',
        height: '100%',
        position: 'absolute',
        top: '0',
        left: '0',
        borderRadius: '10px',
        padding: '1px',
        WebkitMask: 'linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0)',
        WebkitMaskComposite: 'xor',
        maskComposite: 'exclude',
        backgroundBlendMode: 'overlay',
    },
    cardImage: {
        width: '100%',
        height: '100%',
        objectFit: 'cover',
    },
    cardTitle: {
        fontStyle: 'normal',
        fontWeight: 590,
        fontSize: '17px',
        lineHeight: '20px',
        margin: '10px 0',
    },
    divider: {
        border: 'none',
        height: '1px',
    },
    cardText: {
        fontStyle: 'normal',
        fontWeight: 400,
        fontSize: '13px',
        lineHeight: '24px',
        color: 'rgba(255, 255, 255, 0.7)',
    },
}));
