name: Node.js CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile
      - run: yarn run turbo

  merge-check:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile
      - run: yarn run turbo
      - name: Check if build succeeded
        run: |
          if [ ${{ job.status }} == 'failure' ]; then
            echo "::error::Build failed. Please fix the issues before merging."
            exit 1
          fi
